### ISSUE TITLE
Το install.php και το update.php θα πρέπει να ορίζουν το config variable autojudge_connector με default τιμή CodepadConnector (1 άτομο)

### ISSUE THREAD

**Issue by dnna** [maellak/openeclass#108]
Θα πρέπει να προστίθεται η σχετική γραμμή στον πίνακα config ώστε να λειτουργεί σωστά ο κριτής σε νέες εγκαταστάσεις.

**Comment by a123xxsp** [comment]
Οκτωβρίου θα το δω σήμερα 

On January 6, 2015 4:54:20 PM EET, Dimosthenis Nikoudis <notifications@github.com> wrote:
>Θα πρέπει να οριστεί η σχετική γραμμή στον πίνακα config ώστε να
>λειτουργεί σωστά ο κριτής σε νέες εγκαταστάσεις.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/maellak/openeclass/issues/108

-- 
Αποστολή με K-9 Mail από το Android κινητό μου. Συγχωρήστε τη συντομία.

**Comment by dnna** [comment]
Αντώνη έχουμε κάποια εξέλιξη;

**Comment by a123xxsp** [comment]
Συγνώμη γιόρταζε γιος και πατέρας χθες και δεν πρόλαβα. Δεν είναι τίποτα θα το δω σε 1ωρα και θα κάνω και το pull request 

On January 8, 2015 6:29:24 PM EET, Dimosthenis Nikoudis <notifications@github.com> wrote:
>Αντώνη έχουμε κάποια εξέλιξη;
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/maellak/openeclass/issues/108#issuecomment-69205098

-- 
Αποστολή με K-9 Mail από το Android κινητό μου. Συγχωρήστε τη συντομία.

**Comment by dnna** [comment]
Το ξέρω, συνγώμη που πιέζω. Απλά προσπαθώ να κλείσω τα τελευταία τελευταία πραγματάκια της συνεισφοράς, ώστε να σταθεροποιηθεί ο κώδικας και να στρέψουμε την προσοχή μας στην ενσωμάτωση.

**Comment by a123xxsp** [comment]
Δεν υπάρχει καμία πίεση, δικό μου είναι το φταίξιμο μιας δεν ήταν τίποτα μεγάλο για να το αργήσω τόσο,
το έκανα, προσπαθώ να κάνω pull request και τη μία μου βγήκε 404 και την άλλη δεν βλέπει διαφορές,
το προσπαθώ πάλι , καλού κακού έβαλα και τα αρχεία συνημμέναστο install_db.php έχει προστεθεί μία γραμμή (η 1238) και η παλιά 1238 είναι τώρα 1239 κλπκ στο upgrade.php μπήκαν 2 γραμμές οι  2373 & 2374
ελπίζω στο επόμενο 5λεπτο να γίνει και σωστά το pull request

      Απο: Dimosthenis Nikoudis <notifications@github.com>
 Προς: maellak/openeclass <openeclass@noreply.github.com> 
Κοιν.: Antonios Roussos <a123xxsp@yahoo.gr> 
 Στάλθηκε: 10:47 μ.μ. Πέμπτη, 8 Ιανουαρίου 2015
 Θέμα: Re: [openeclass] Το install.php και το update.php θα πρέπει να ορίζουν το config variable autojudge_connector με default τιμή CodepadConnector (1 άτομο) (#108)
   
Το ξέρω, συνγώμη που πιέζω. Απλά προσπαθώ να κλείσω τα τελευταία τελευταία πραγματάκια της συνεισφοράς, ώστε να σταθεροποιηθεί ο κώδικας και να στρέψουμε την προσοχή μας στην ενσωμάτωση.—

**Comment by a123xxsp** [comment]
έγινε και το Pull request:)καλό βράδυ
      Απο: Antonios Roussos <a123xxsp@yahoo.gr>
 Προς: maellak/openeclass <reply@reply.github.com>; maellak/openeclass <openeclass@noreply.github.com> 
 Στάλθηκε: 11:36 μ.μ. Πέμπτη, 8 Ιανουαρίου 2015
 Θέμα: Σχετ: [openeclass] Το install.php και το update.php θα πρέπει να ορίζουν το config variable autojudge_connector με default τιμή CodepadConnector (1 άτομο) (#108)
   
Δεν υπάρχει καμία πίεση, δικό μου είναι το φταίξιμο μιας δεν ήταν τίποτα μεγάλο για να το αργήσω τόσο,
το έκανα, προσπαθώ να κάνω pull request και τη μία μου βγήκε 404 και την άλλη δεν βλέπει διαφορές,
το προσπαθώ πάλι , καλού κακού έβαλα και τα αρχεία συνημμέναστο install_db.php έχει προστεθεί μία γραμμή (η 1238) και η παλιά 1238 είναι τώρα 1239 κλπκ στο upgrade.php μπήκαν 2 γραμμές οι  2373 & 2374
ελπίζω στο επόμενο 5λεπτο να γίνει και σωστά το pull request

 

     Απο: Dimosthenis Nikoudis <notifications@github.com>
 Προς: maellak/openeclass <openeclass@noreply.github.com> 
Κοιν.: Antonios Roussos <a123xxsp@yahoo.gr> 
 Στάλθηκε: 10:47 μ.μ. Πέμπτη, 8 Ιανουαρίου 2015
 Θέμα: Re: [openeclass] Το install.php και το update.php θα πρέπει να ορίζουν το config variable autojudge_connector με default τιμή CodepadConnector (1 άτομο) (#108)
   
Το ξέρω, συνγώμη που πιέζω. Απλά προσπαθώ να κλείσω τα τελευταία τελευταία πραγματάκια της συνεισφοράς, ώστε να σταθεροποιηθεί ο κώδικας και να στρέψουμε την προσοχή μας στην ενσωμάτωση.—

**Comment by dnna** [comment]
Thanks!
