### ISSUE TITLE
Προβλημα με την εξοδο απο λογαριασμο.

### ISSUE THREAD

**Issue by ManosGEM** [maellak/openeclass#116]
Οταν κανει εισοδο με το account σου , αν κανεις αποσυνδεση-εξοδο απο το λογαριασμο σου και χωρις να κλεισεις τον browser πατησεις εισοδο , σε βαζει αυτοματα στο τελευταιο account απο το οποιο εκανες εξοδο. Ουσιαστικα αν δεν κλεισεις ολο τον browser δεν γινεται εξοδος απο το λογαριασμο σου. 
Το προβλημα το παρατηρησα στους εξης browsers : Internet Explorer , Google Chrome , Mozilla Firefox (win7 & ubuntu linux 14) .

απο αυτα που ξερω περι του θεματος , δεν γινεται σωστα το κλεισιμο του session.

**Comment by dnna** [comment]
Καλησπέρα,

Παρακαλώ γράψτε την παρατήρηση σας στο επίσημο repository του openeclass https://github.com/gunet/openeclass. Το συγκεκριμένο repo αφορούσε την ανάπτυξη χαρακτηριστικών στα πλαίσια του έργου "Μονάδες Αριστείας ΕΛΛΑΚ" και δεν συντηρείται. cc @axilleas
