### ISSUE TITLE
Δυνατότητα για edit σεναρίων (1 άτομο)

### ISSUE THREAD

**Issue by dnna** [maellak/openeclass#68]
Homework 4ου workshop

**Comment by dnna** [comment]
Αν έχω καταλάβει καλά αυτό είναι έτοιμο και εκκρεμεί να γίνει το pull request; Σοφία θα το κάνεις εσύ;

**Comment by dnna** [comment]
ping @axilleas σε περίπτωση που χρειαστεί κάποια βοήθεια με το PR

**Comment by grglaz** [comment]
ναι σωστα καταλαβες Δημο. Λογικα η Σοφια απλα δεν εχει βρει χρονο ακομα...

**Comment by 3DSo** [comment]
το έκανα pull προ ολίγου...

2015-01-03 22:00 GMT+02:00 George Lazarou <notifications@github.com>:

> ναι σωστα καταλαβες Δημο. Λογικα η Σοφια απλα δεν εχει βρει χρονο ακομα...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maellak/openeclass/issues/68#issuecomment-68607457>.
>



-- 
Best regards,
Rousou Sofia

**Comment by dnna** [comment]
PR reference: https://github.com/maellak/openeclass/pull/103

**Comment by dnna** [comment]
@3DSo @grglaz έκανα κάποιες μικροαλλαγές στον κώδικα σας για να είναι πιο consistent με τη σελίδα δημιουργίας σεναρίου (δεν υπάρχει extra σενάριο στο τέλος, το X κρύβεται στο πρώτο σενάριο, ο κριτής κρύβεται όταν ο χρήστης κλείσει το "περισσότερες επιλογές" κτλ.)

Ένα θέμα που παρατηρώ είναι ότι ο καθηγητής δεν μπορεί να αλλάξει τη γλώσσα του αυτόματου κριτή από το edit. Θα μπορούσε να το δει κάποιος από εσάς;

**Comment by dnna** [comment]
Άκυρο, τελικά το πρόσθεσα εγώ. Το task κλείνει. Ευχαριστούμε και τους δύο! Keep it up :+1:
