### ISSUE TITLE
Δημιουργία σελίδας κατατάξεων (3 άτομα)

### ISSUE THREAD

**Issue by dnna** [maellak/openeclass#70]
Ο καθηγητής θα πρέπει να έχει την επιλογή να δημιουργήσει ένα report κατατάξεων για όλους τους φοιτητές που υπέβαλαν εργασία. Το report θα έχει μια μορφή αντίστοιχη με την παρακάτω και θα ανεβαίνει αυτόματα στα έγγραφα του μαθήματος.
![summary_report](https://cloud.githubusercontent.com/assets/1296821/4994862/852671a0-69c5-11e4-9fd6-8534987da0d7.png)

**Comment by Loukas1987** [comment]
Καλησπέρα σας και Χρόνια σας Πολλά. Όσον αφορά το 1ο bug με την μη εμφάνιση των μεταλλίων στο pdf που δημιουργείται, έριξα μια ματιά στον κώδικα και διαπίστωσα ότι το ότι δεν εμφανίζονται τα μετάλλια είναι θέμα του tcpdf. Και αυτό γιατί υπάρχει εντολή που παρουσιάζεις ξεχωριστά html κώδικα και ξεχωριστή εντολή που εκτυπώνει .svg εικόνες ή .jpg εικόνες.

Για html κώδικα:
π.χ.
Α.  $pdf->writeHTML($report_details, true, false, true, false, '');
    
Για svg εικόνα:
π.χ.
Β.  
$pdf-> ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Gold_medal_with_cup.svg', $x=35, $y=39.5, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
 ή    
π.χ. (για .jpg)
$pdf->Image('images/image_demo.jpg', $x, $y, $w, $h, 'JPG', '', '', false, 300, '', false, false, 0, $fitbox, false, false);

Συνθήκη για το πότε θα εμφανίζεται η .svg εικόνα , συνθήκη για το πότε θα εμφανίζεται ο κώδικας Β  ανάλογα με το $i δεν βρήκα.
Η μόνη λύση,ίσως, με βάση την εικόνα που έχω, που μπορεί να γίνει είναι να μπαίνει χειροκίνητα η εικόνα αλλάζοντας το $x και το  $y στην παρένθεση για κάθε μετάλλιο (στην ουσία επειδή το κάθε εικονίδιο θα είναι σε διαφορετική γραμμή , το $x μένει σταθερό σαν συντεταγμένη και αλλάζει μόνο το $y.

 $pdf->ImageSVG  ανάλογα με την θέση που πρέπει να μπει στην γραμμή κατάταξης.

Αλλά αυτό δεν μπορεί να γίνεται δυναμικά αν δεν μπει μια συνθήκη....

Αν μπουν όλες μαζί οι εικόνες θα έχει σωστή μορφή ο πίνακας μόνο όταν έχουν γίνει 6 εγγραφές και πάνω στον πίνακα κατάταξης...

 $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Gold_medal_with_cup.svg', $x=35, $y=39.5, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
    $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Gold_medal_with_cup.svg', $x=35, $y=45, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
    $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Silver_medal_with_cup.svg', $x=35, $y=50, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
    $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Silver_medal_with_cup.svg', $x=35, $y=55, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
    $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Bronze_medal_with_cup.svg', $x=35, $y=60, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  
    $pdf->ImageSVG($file='C:/xampp/htdocs/openeclass/images/work_medals/Bronze_medal_with_cup.svg', $x=35, $y=65, $w='4px', $h='4px', $align='', $palign='', $border=1, $fitonpage=false);  

Ίσως αν εξ' αρχής δημιουργείται ένας πίνακας με έξι στήλες , άσχετα αν υπάρχουν λιγότεροι χρήστες-λιγότερες εργασίες, με κενές γραμμές όσον αφορά τα δεδομένα όταν δεν έχει καταχωρηθεί εργασία αλλά με τοποθετημένο το μετάλλιο στο rank...

Ελπίζω να μην σας μπέρδεψα με το σκεπτικό μου...Θα σας παρακαλούσα την γνώμη σας....

**Comment by dnna** [comment]
Όχι νομίζω μπλέκει πολύ αν αρχίσουμε να πειράζουμε το x και y για να βάλουμε τα μετάλλια. Σε αυτή την περίπτωση θα έλεγα ας αντικαταστήσουμε τις εικόνες των μεταλλίων με ASCII όπως αυτά: http://character-code.com/pictograph-html-codes.php που λογικά δε θα έχουν πρόβλημα.

Δεν το ήξερα ότι είναι τόσο πολύπλοκες οι εικόνες με το tcpdf (είχα συνηθήσει από άλλα tools όπως το wkhtmltopdf που δεν είχαν τέτοιο θέμα).

**Comment by giannisdag** [comment]
ok, λύθηκε λογικά το πρόβλημα, βασισμένο πάλι στην λύση που έδωσε ο Λευτέρης στην αντίστοιχη περίπτωση, είναι θέμα περισσότερο του path, για να μην αναλύω περισσότερο, απλά πρέπει οι εικόνες να γίνουν scale σε 30Χ30, γιατί δεν αλλάζουν οι διαστάσεις τους στο pdf όπως στην html με το width. Θα ανεβάσω σε λίγο τον κώδικα

**Comment by dnna** [comment]
Ωραίοι :+1: 
Πριν ανεβάσεις τον κώδικα αν μπορείς δες και ένα μικρό αισθητικό θεματάκι (δεν κεντράρεται σωστά) στο παρακάτω screenshot και νομίζω τελειώσαμε με το task
![not_centered](https://cloud.githubusercontent.com/assets/1296821/5602623/d2afe646-9363-11e4-8901-c603ac6b941d.png)

**Comment by giannisdag** [comment]
έχει ήδη γίνει στο προτελευταίο commit. Περιμένω τα images από τον Λουκά και τελειώσαμε

**Comment by dnna** [comment]
https://github.com/maellak/openeclass/pull/104
