### ISSUE TITLE
Δημιουργία online code editor (2 άτομα)

### ISSUE THREAD

**Issue by dnna** [maellak/openeclass#73]
Απλός code editor με syntax highlighting και δυνατότητα ανεβάσματος εργασίας χωρίς να χρειάζεται τοπική έκδοση του αρχείου στον υπολογιστή του φοιτητή

**Comment by dnna** [comment]
Δημήτρη δυστυχώς πλέον ο χρόνος μας πιέζει ασφυκτικά και δε νομίζω ότι θα προλάβουμε να ενσωματώσουμε τη συγκεκριμένη συνεισφορά στα πλαίσια αυτού του batch που θα τους στείλουμε. Αν την ολοκληρώσεις πάντως μπορούμε να τους τη δώσουμε σαν ένα ξεχωριστό feature αμέσως μόλις ενσωματώσουν τον κριτή.

Σε κάθε περίπτωση, προσπάθησε να ανεβάσεις ότι έχεις φτιάξει μέχρι την Κυριακή ώστε να είμαστε τυπικά καλυμμένοι και εννοείται ότι θα είμαστε εδώ αν θέλεις να τη συνεχίσεις και να τους τη δώσουμε.

**Comment by dandrits** [comment]
Δημοσθένη νόμιζα ότι έχουμε μέχρι τη Δευτέρα. Λυπάμαι που δεν το έχουμε έτοιμο. Θα κάνω αν είναι Pull request με το -μη λειτουργικό- κώδικα που έχουμε αν θες και μπορώ να συνεχίσουμε να το δουλεύουμε

**Comment by dnna** [comment]
Κλείνω το issue για να φαίνεται ότι έκλεισε. Θα συννενοηθούμε μεταξύ μας την Τρίτη για τη συνέχεια.
